version: '3.0'

services:
  gameapp-db:
    image: mysql:8.0
    ports:
      - "3320:3306"
    container_name: gameapp-db
    volumes:
      - gameappdb:/var/lib/mysql
    restart: always
    command: [ 'mysqld','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: wontbeused
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: wontbeused
volumes:
  gameappdb:
    driver: local