version: '3.0'

services:
  gameapp-redis:
    image: bitnami/redis:6.2
    container_name: gameapp-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - gameapp-redis-data:/data
  gameapp-db:
    image: mysql:8.0
    ports:
      - "3320:3306"
    container_name: gameapp-db
    volumes:
      - gameappdb:/var/lib/mysql
    restart: always
    command: [ 'mysqld','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: wontbeused
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: wontbeused
volumes:
  gameappdb:
    driver: local
  gameapp-redis-data:
    driver: local